[package]
name = "kkr-python"
version.workspace = true
edition.workspace = true

[lib]
name = "kkr"
crate-type = ["cdylib"]

[dependencies]
kkr-core.workspace = true
pyo3 = { version = "0.20", features = ["extension-module"] }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
